var codes = {};

/* Special cases */
codes.UNKNOWN_FAILURE = 'UNKNOWN_FAILURE';
codes.SUCCESS = 0;

/* Database related */
codes.DATABASE_FAILURE = 'DATABASE_FAILURE';

/* User related */
codes.USER_NOT_REGISTERED = 'USER_NOT_REGISTERED';
codes.USER_ALREADY_REGISTERED = 'USER_ALREADY_REGISTERED';
codes.USER_ALREADY_SIGNED = 'USER_ALREADY_SIGNED';
codes.USER_NOT_SIGNED = 'USER_NOT_SIGNED';
codes.UNAUTHORIZED = 'UNAUTHORIZED';

/* Game related */
codes.GAME_NOT_FOUND = 'GAME_NOT_FOUND';
codes.GAME_NOT_READY = 'GAME_NOT_READY';
codes.NO_CURRENT_GAMES = 'NO_CURRENT_GAMES';

/* Season related */
codes.NO_SEASONS_FOUND = 'NO_SEASONS_FOUND';

module.exports = codes;